### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by Evolutiounx** [Tustin/fortnite-php#1]
Hi
First of all thanks for this awesome API.
So the problem I'm having with it is that after many requests with an epic games account it gives me an error saying that I have too many connections going on.
Is that a way to logout after retrieving data with the api?
This is the error:
[https://i.gyazo.com/84e4efe60a54bd90b12d835a0b0826ef.png](https://i.gyazo.com/84e4efe60a54bd90b12d835a0b0826ef.png)

**Comment by Tustin** [comment]
Weird. If I had to guess, maybe there's too many different OAuth tokens associated with your IP/account? If you're generating new tokens each time instead of refreshing an existing one, that would probably explain the error. I have a method that refreshes an existing token and you can see an example of how to set that up by taking a look at my example stat tracker site: https://github.com/Tustin/FortniteTracker/blob/master/app/Http/Middleware/OAuthUpdater.php#L22
