### ISSUE TITLE
2-Factor Authentication

### ISSUE THREAD

**Issue by nice-rain** [Tustin/fortnite-php#35]
When I try to login, I receive the following error message:

Two-Factor authentication required to process request.

Is there any way to support 2-factor authentication?

**Comment by monkeydioude** [comment]
Do you really need to ?

You could make an other account just for requesting the API

**Comment by Krokit** [comment]
@monkeydioude Yes you can but if you want to have full access to stats like STW, Battle Pass, you will need to buy them for an account which is not going to be played.

**Comment by nice-rain** [comment]
I'm sure the API call for two-factor authentication is private. They'd have no need to use that within the app, so I am not sure we'll be able to find it to be honest.

**Comment by Tustin** [comment]
Started working on this with e0da9392f219773ff5a50de75a51b40cf7f2bf8e, but ran into an annoying issue. For some reason, the 2FA response keeps saying 'invalid credentials', but the actual error seems to indicate that `grant_type` is invalid, which isn't correct since I'm using the same one they do to validate the 2FA code. If anyone would like to mess with it, you can pull in the code from the using the dev-master flag for composer like so: `composer require tustin/fortnite-php=dev-master`. This is an example of using the new auth code:
```php
use Fortnite\Auth;
use Fortnite\Exception\TwoFactorAuthRequiredException;

$email = '';
$password = '';

try {
    $auth = Auth::login($email, $password);
} catch (TwoFactorAuthRequiredException $e) {
    $code = readline('Enter 2FA code: ');
    $auth = Auth::login($email, $password, $e->getChallenge(), $code);
}
```

**Comment by Krokit** [comment]
@Tustin  Check discord. a friend request from Bul*****Hea**r 😄

**Comment by Tustin** [comment]
@dzinks2009 I haven't tried looking at it since, but I recommend just making a new account and using that if possible. I'm probably just missing something really stupid that I didn't notice when I tried to add it. I'll have a look at it again soon to see if I can find the issue.

**Comment by Erlandys** [comment]
For two-factor-auth, instead of "**opt**" **grant_type**", try to use "**exchange_code**" type.
**grant_type** post parameter and **exchange_code** post parameter.
To retrieve **exchange_code**, load this: _https://accounts.epicgames.com/login/showPleaseWait?client_id=...._
And from loaded html, parse code:
`com.epicgames.account.web.widgets.loginWithExchangeCode('**...**')`

**Comment by Tustin** [comment]
So it seems like X-Epic-Device-ID is actually the culprit because if I use my phone's device ID, it doesn't prompt 2fa and it works fine. When I change one character in the ID and try to login, it seems to authenticate but for some reason, some API endpoints throw a 401 with an authentication error. It doesn't make much sense but in the rewrite, I've added an optional deviceId param to `login()` so you can pass that ID if you have it to bypass the 2fa error. If I can figure out why custom device Ids fail, I'll add full support for 2fa.

**Comment by Tustin** [comment]
Scratch that, got it working. Stupid mistake on my part.
![](https://i.imgur.com/sMIwFnV.png)

**Comment by olli3** [comment]
so if we composer update will this work now ?

**Comment by RobertoGraham** [comment]
> Stupid mistake on my part

@Tustin Sorry to bump a resolved issue but do you remember what the mistake was? I'm getting the same annoying `errors.com.epicgames.account.invalid_account_credentials` while trying to implement this in another library

**Comment by olli3** [comment]
++ on comment above,  is this fixed or not ?

**Comment by RobertoGraham** [comment]
@olli3 Got it working in my library. The crux of it is to use the same `X-Epic-Device-ID` header value for both the `password` grant_type request and the `otp` grant_type request. I've written a language-agnostic explanation [here](https://github.com/RobertoGraham/fortnite-2/wiki/Two-factor-authentication-(2FA)-using-a-one-time-password-(OTP)#language-agnostic-2fa-flow-explanation), it assumes the reader is already familiar with Fortnite authentication requests
